version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel_app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel

networks:
  laravel:
